<?php

function cd_contact_schema() {
  $schema['cd_contact'] = array(
    'fields' => array(
      'cid' => array(
        'type' => 'serial',
        'not null' => TRUE,
      ),
      'name' => array(
        'type' => 'varchar',
        'length' => 50,
        'not null' => TRUE,
      ),
      'message' => array(
        'type' => 'varchar',
        'length' => 250,
        'not null' => TRUE,
      ),
    ),
    'primary key' => array('cid'),
  );
  return $schema;
}
